import type { CatalogProduct } from "./catalog.types";

export const catalogProducts: readonly CatalogProduct[] = [
  {
    id: "macbook-air-m4",
    slug: "macbook-air-m4-13",
    name: "MacBook Air M4 13\"",
    category: "Laptop",
    price: 26_990_000,
    compareAtPrice: 28_990_000,
    imageUrl: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=1200&q=85",
    imageAlt: "Laptop nhôm màu bạc mở trên bàn làm việc tối giản",
    badge: "Nexora Pick",
    verdict: "Mỏng nhẹ, pin dài và đủ mạnh cho phần lớn ngày làm việc.",
    specs: ["Apple M4", "RAM 16 GB", "Pin đến 18 giờ"],
    featured: true,
  },
  {
    id: "asus-zenbook-14-oled",
    slug: "asus-zenbook-14-oled-ux3405",
    name: "ASUS Zenbook 14 OLED",
    category: "Laptop",
    price: 24_490_000,
    compareAtPrice: 26_990_000,
    imageUrl: "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=1200&q=85",
    imageAlt: "Laptop mỏng màu xám hiển thị màn hình sáng trên bàn gỗ",
    badge: "Màn hình đẹp",
    verdict: "Lựa chọn Windows cân bằng cho người cần màn hình xuất sắc.",
    specs: ["OLED 3K 120 Hz", "Intel Core Ultra 7", "1,2 kg"],
    featured: true,
  },
  {
    id: "iphone-16-pro",
    slug: "iphone-16-pro",
    name: "iPhone 16 Pro",
    category: "Điện thoại",
    price: 28_490_000,
    compareAtPrice: 30_990_000,
    imageUrl: "https://images.unsplash.com/photo-1592750475338-74b7b21085ab?auto=format&fit=crop&w=1200&q=85",
    imageAlt: "Điện thoại màu tối đặt nghiêng trên bề mặt trung tính",
    badge: "Creator choice",
    verdict: "Camera ổn định và hiệu năng bền cho người làm nội dung.",
    specs: ["A18 Pro", "Camera tele 5x", "Màn hình 120 Hz"],
    featured: true,
  },
  {
    id: "galaxy-s25",
    slug: "samsung-galaxy-s25",
    name: "Samsung Galaxy S25",
    category: "Điện thoại",
    price: 20_990_000,
    compareAtPrice: 22_990_000,
    imageUrl: "https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?auto=format&fit=crop&w=1200&q=85",
    imageAlt: "Điện thoại Samsung màu tím nhạt nhìn từ mặt lưng",
    badge: "AI tiện dụng",
    verdict: "Nhỏ gọn, màn hình sáng và nhiều tính năng hỗ trợ hằng ngày.",
    specs: ["Snapdragon 8 Elite", "Galaxy AI", "7 năm cập nhật"],
    featured: true,
  },
  {
    id: "sony-wh1000xm5",
    slug: "sony-wh-1000xm5",
    name: "Sony WH-1000XM5",
    category: "Âm thanh",
    price: 7_490_000,
    compareAtPrice: 8_490_000,
    imageUrl: "https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=1200&q=85",
    imageAlt: "Tai nghe chụp tai màu đen trên nền tối",
    badge: "Chống ồn tốt",
    verdict: "Không gian tập trung đáng tin cậy cho văn phòng và chuyến bay.",
    specs: ["ANC thích ứng", "Pin 30 giờ", "Multipoint"],
    featured: true,
  },
  {
    id: "logitech-mx-master-3s",
    slug: "logitech-mx-master-3s",
    name: "Logitech MX Master 3S",
    category: "Phụ kiện",
    price: 2_190_000,
    compareAtPrice: 2_490_000,
    imageUrl: "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?auto=format&fit=crop&w=1200&q=85",
    imageAlt: "Chuột công thái học màu đen cạnh bàn phím",
    verdict: "Chuột làm việc yên tĩnh, chính xác và chuyển thiết bị rất nhanh.",
    specs: ["Cảm biến 8K DPI", "Kết nối 3 thiết bị", "Cuộn MagSpeed"],
    featured: true,
  },
];
